<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="GStock.aspx.cs" Inherits="Medicare.Admin.GStock" %>
<asp:Content ID="Content1" ContentPlaceHolderID="c1" runat="server">

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="CenteredGrid" DataKeyNames="pid" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="pid" HeaderText="pid" InsertVisible="False" ReadOnly="True" SortExpression="pid" />
            <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
            <asp:BoundField DataField="desc" HeaderText="desc" SortExpression="desc" />
            <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
            <asp:BoundField DataField="qty" HeaderText="qty" SortExpression="qty" />
            <asp:BoundField DataField="image" HeaderText="image" SortExpression="image" />
            <asp:BoundField DataField="cat" HeaderText="cat" SortExpression="cat" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
UpdateCommand="UPDATE [product] set [name]=@name, [desc]=@desc,[price]=@price, [qty]=@qty, [image]=@image where pid=@pid"
     DeleteCommand="DELETE from [product] where pid=@pid"
             
         SelectCommand="SELECT * FROM [product] where cat='General'"></asp:SqlDataSource>

    <style type="text/css">
    .CenteredGrid { 
        width:800px;
        margin-left:auto;
        margin-right:auto;
        text-align:center;
    }
        .CenteredGrid td{
            padding:10px;
            border:1px solid #c1c1c1;
            color:#444;
            font-size:1em;

        }
        .CenteredGrid th {
            padding: 4px 2px;
            color: #707083;
            text-shadow: 1px 1px 0px #ffffff;
            background: -weblit-gradient(linear,left bottom,left top,color-stop(0,#e5e5e9),color-stop(1,#fbfbfc));
            border: 1px solid #c1c1c1;
            font-size: 1em;
            text-align: center;
        }
        .CenteredGrid th a{
            color:white;
            text-decoration:none;
        }
        .CenteredGrid th a:hover{
            color:#444;
            text-decoration:none;
        }
    </style>




</asp:Content>
