<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="Stock.aspx.cs" Inherits="Medicare.Admin.Stock" %>
<asp:Content ID="Content1" ContentPlaceHolderID="c1" runat="server">
    <style type="text/css">
    .CenteredGrid { 
        width:800px;
        margin-left:auto;
        margin-right:auto;
        text-align:center;
    }
        .CenteredGrid td{
            padding:10px;
            border:1px solid #c1c1c1;
            color:#444;
            font-size:1em;

        }
        .CenteredGrid th {
            padding: 4px 2px;
            color: #707083;
            text-shadow: 1px 1px 0px #ffffff;
            background: -weblit-gradient(linear,left bottom,left top,color-stop(0,#e5e5e9),color-stop(1,#fbfbfc));
            border: 1px solid #c1c1c1;
            font-size: 1em;
            text-align: center;
        }
        .CenteredGrid th a{
            color:white;
            text-decoration:none;
        }
        .CenteredGrid th a:hover{
            color:#444;
            text-decoration:none;
        }
    </style>

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="pid" DataSourceID="SqlDataSource1" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" HorizontalAlign="Center" EditRowStyle-HorizontalAlign="Center" CssClass="CenteredGrid table table-striped table-bordered table-hover"  AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
    <Columns >
        <asp:BoundField DataField="pid" HeaderText="pid" InsertVisible="False" ReadOnly="True" SortExpression="pid" />
        <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
        <asp:BoundField DataField="desc" HeaderText="desc" SortExpression="desc" />
        <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
        <asp:BoundField DataField="qty" HeaderText="qty" SortExpression="qty" />
        <asp:BoundField DataField="image" HeaderText="image" SortExpression="image" />

       
        <asp:BoundField DataField="cat" HeaderText="cat" SortExpression="cat" />

       
    </Columns>

<EditRowStyle HorizontalAlign="Center"></EditRowStyle>

        <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#0000" HorizontalAlign="Center" />
        <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
        <RowStyle BackColor="White" ForeColor="#330099" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
        <SortedAscendingCellStyle BackColor="#FEFCEB" />
        <SortedAscendingHeaderStyle BackColor="#AF0101" />
        <SortedDescendingCellStyle BackColor="#F6F0C0" />
        <SortedDescendingHeaderStyle BackColor="#7E0000" />
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
     UpdateCommand="UPDATE [product] set [name]=@name, [desc]=@desc,[price]=@price, [qty]=@qty, [image]=@image, [cat]=@cat where pid=@pid" 
     DeleteCommand="DELETE from [product] where pid=@pid"
    SelectCommand="SELECT * FROM [product]"></asp:SqlDataSource>

</asp:Content>
